### ISSUE TITLE
Marshmallow schema with many=True seems to be ignored

### ISSUE THREAD

**Issue by imgos** [apryor6/flask_accepts#41] opened 2019-10-14 14:06 UTC
Using a marshmallow schema with `many=True` seems to be ignored in both validation and the swagger output.

```python3
my_ns = my_api.namespace("roles")

@my_ns.route("/")
class MyResource(flask_restplus.Resource):
    @flask_accepts.accepts(schema=MyRequestSchema(many=True), api=my_ns)
    @flask_accepts.responds(schema=MyResponseSchema(many=True), api=my_ns)
    def put():
        return []
```

For this example, the endpoint will not accept a list at the top-level of the request body as I intend.  It just accepts an object as if `many=True` wasn't there.

I believe in versions prior to 0.14.2 the validation worked, but the swagger output was still incorrect.

**Comment by apryor6** [comment] 2019-10-14 14:33
On the latest (0.14.2) version I observe that the Swagger documentation does not correctly capture `many=True`, but the validation does work. Can you confirm this is what you experience?

Here is the script I used:

```
from dataclasses import dataclass
from marshmallow import fields, Schema, post_load
from flask import Flask, jsonify, request
from flask_accepts import accepts, responds


@dataclass
class Widget:
    foo: str
    baz: int


class WidgetSchema(Schema):
    foo = fields.String(default="test value")
    baz = fields.Integer(default=422)

    @post_load
    def make(self, data, **kwargs):
        return Widget(**data)


def create_app(env=None):
    from flask_restplus import Api, Namespace, Resource

    app = Flask(__name__)
    api = Api(app)

    @api.route("/restplus/make_a_widget")
    class WidgetResource(Resource):
        @accepts(
            dict(name="some_arg", type=str), schema=WidgetSchema(many=True), api=api
        )
        @responds(schema=WidgetSchema(many=True), api=api)
        def post(self):
            from flask import jsonify

            return request.parsed_obj

    return app


app = create_app()
if __name__ == "__main__":
    app.run(debug=True)
```

and then the curl request:

```
curl -X POST "http://127.0.0.1:5000/restplus/make_a_widget" -H "accept: application/json" -H "Content-Type: application/json" -d "[{ \"baz\": 422, \"foo\": \"test value\"},{ \"baz\": 1, \"foo\": \"another value\"}]"
```

yields a successful response:

```
[
    {
        "baz": 422,
        "foo": "test value"
    },
    {
        "baz": 1,
        "foo": "another value"
    }
]
```

Assuming this is what you observe as well, the issue is limited to the Swagger documentation itself, and I suspect the fix is simply to make sure if `many=True` that a `List` is wrapped around the converted schema. Should be straightforward to fix.

**Comment by imgos** [comment] 2019-10-14 23:49
I agree, your example functions correctly and only the swagger documentation is incorrect.

In a more complex app, I still have a problem with the `many=True` input.  It is likely an interaction with another library and not a problem with this one.

Thanks for publishing this library, it is quite helpful and easy to use!

**Comment by apryor6** [comment] 2019-10-15 12:56
I just tried a couple of things and wasn't quite able to get it working the way I'd like. I'll need to spend some more time on it later.

Basically it appears there is no issue with nested objects/lists -- the issue is isolated to documentation of top-level `many=True`.

I would point out that perhaps a more specific solution would be to declare a separate schema that explicitly wraps a list of your objects. This has the benefit of allowing you the control the model name and add additional metadata if necessary; however, it is more verbose and may not do what you want. I only bring it up as an alternative for the time being:

```
from dataclasses import dataclass
from marshmallow import fields, Schema, post_load
from flask import Flask, jsonify, request
from flask_accepts import accepts, responds


@dataclass
class Widget:
    foo: str
    baz: int


class WidgetSchema(Schema):
    foo = fields.String(default="test value")
    baz = fields.Integer(default=422)

    @post_load
    def make(self, data, **kwargs):
        return Widget(**data)


class WidgetList(Schema):
    widgets = fields.List(fields.Nested(WidgetSchema))


def create_app(env=None):
    from flask_restplus import Api, Namespace, Resource

    app = Flask(__name__)
    api = Api(app)

    @api.route("/restplus/make_a_widget")
    class WidgetResource(Resource):
        @accepts(dict(name="some_arg", type=str), schema=WidgetList, api=api)
        @responds(schema=WidgetList, api=api)
        def post(self):
            from flask import jsonify

            return request.parsed_obj["widgets"]

    return app


app = create_app()
if __name__ == "__main__":
    app.run(debug=True)

```

**Comment by imgos** [comment] 2019-10-15 16:57
I am generally opposed to top-level lists, but in this case I have no choice but to keep to retain compatibility.

I was able to determine the cause of my list validation failure.  It was due to having `RESTPLUS_VALIDATE` set to `True` in the app configuration.  Once I set it to `False`, then the issue is reduced to just swagger being incorrect.

I do not recall why `RESTPLUS_VALIDATE` was set and in my case disabling it seems fine.  Should it be allowed while using `flask_accepts`, though?  Everything seems to work okay with it set to `True` except for top-level list validation.

With it `True`, the restplus Resource's `validate_payload` fails while trying to validate the list as a model.

**Comment by imgos** [comment] 2019-10-15 21:21
For posterity, this example exhibits the validation issue I saw:

```python3
from dataclasses import dataclass
from marshmallow import fields, Schema, post_load, EXCLUDE
from marshmallow.validate import Range
from flask import Flask, request
from flask_accepts import accepts, responds


@dataclass
class Widget:
    foo: str
    baz: int


class WidgetSchema(Schema):
    foo = fields.String(default="test value")
    baz = fields.Integer(default=422)

    @post_load
    def make(self, data, **kwargs):
        return Widget(**data)


def create_app(env=None):
    from flask_restplus import Api, Resource

    app = Flask(__name__)
    app.config["RESTPLUS_VALIDATE"] = True

    api = Api(app)

    @api.route("/restplus/make_a_widget")
    class WidgetResource(Resource):
        @accepts(schema=WidgetSchema(many=True), api=api)
        @responds(schema=WidgetSchema(many=True), api=api)
        def put(self):
            return request.parsed_obj

    return app


app = create_app()

if __name__ == "__main__":
    app.run(debug=True)
```

**Comment by apryor6** [comment] 2019-10-15 21:24
For the record I consider my above solution to be a short term fix and not the actual solution. I don’t see any reason why this can’t be properly supported in the documentation, unless Swagger does not support lists of top level models as a documented type? I’ve personally never used it in this way.

**Comment by VolodyaEsk** [comment] 2019-11-28 17:50
@apryor6 so you think it is a marshmallow issue or swagger, not flask_accepts, correct?

Looks similar to 
https://stackoverflow.com/questions/58484417/flask-marshmallow-nested-schema-with-many-true-not-working

**Comment by VolodyaEsk** [comment] 2019-12-04 08:12
This issue can be closed as resolved. 
The fix - https://github.com/apryor6/flask_accepts/pull/51

**Closed** 2019-12-08 21:56 UTC
Labels: bug

**Comment by VolodyaEsk** [comment] 2019-12-09 10:15
@apryor6 
Can you bump up version of the package and release new version on PyPI?

**Comment by apryor6** [comment] 2019-12-09 13:43
Yes, apologies for the delay!

https://pypi.org/project/flask-accepts/0.15.4/

**Comment by VolodyaEsk** [comment] 2019-12-09 14:28
Thank you.
